{% set version = "1.14.0" %}
{% set buildnumber = 0 %}

package:
  name: tensorflow
  version: {{version}}

build:
  script_env:
    - TF_WHL
  number: {{buildnumber}}
  script: pip install --no-deps {{TF_WHL}}

requirements:
  build:
    - python
    - pip
  run:
    - python
    - pip
    - absl-py >=0.7.0
    - astor >=0.6.0
    - gast >=0.2.0
    - google-pasta >=0.1.6
    - keras-applications >=1.0.6
    - keras-preprocessing >=1.0.5
    - numpy >=1.14.5,<2.0
    - protobuf >=3.6.1
    - six >=1.10.0
    - tensorboard >=1.14.0,<1.15.0 
    - tensorflow-estimator >=1.14.0rc0,<1.15.0rc0 
    - termcolor >=1.1.0
    - wrapt >=1.11.1

test:
  imports:
    - tensorflow

about:
  home: http://tensorflow.org/
  license: Apache 2.0
  license_family: Apache
  summary: TensorFlow is a machine learning library
  description: |
    TensorFlow provides multiple APIs.The lowest level API, TensorFlow Core
    provides you with complete programming control.
  dev_url: https://github.com/tensorflow/tensorflow
  doc_url: https://www.tensorflow.org/get_started/get_started
  doc_source_url: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/docs_src
